
###
### This returs two token one authToken and one refreshToken
### use auth token to make request to /posts, it will expirt after 3 min
### after 3 min the calls would fails, during that time, use the refresh token u got from this one and
### invoke the /token call, that would return a new authToken,
### use that token to make the call it would succeed, every 3 min we need to refresh the token using the original refresh token
### logic is refresh token does not expire, we need to manually evict it by making a logout call

POST http://localhost:4000/login
Content-Type: application/json

{
"userName": "Mani"
}

### The beaer token is what is got from above login
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6Ik1hbmkiLCJpYXQiOjE2MjU3ODMyNjIsImV4cCI6MTYyNTc4MzQ0Mn0.P7kkgX_SpkOOkG5zeVLJ9PU0fSTgeOiNrE-9Yt7samI
### The beaer token is what is got from above login
### Another domain and service

GET http://localhost:5000/books
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6Ik1hbmkiLCJpYXQiOjE2MjU3ODMyNjIsImV4cCI6MTYyNTc4MzQ0Mn0.P7kkgX_SpkOOkG5zeVLJ9PU0fSTgeOiNrE-9Yt7samI

### use refresh token when the above token expiries in 3 min
POST http://localhost:4000/token
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6Ik1hbmkiLCJpYXQiOjE2MjU3ODEzODJ9.JE1svw_bwkxWoGb23tfZPe497Pu2cqCCq7UVW4xp7R8"
}


### To delete the refresh token make an explicit logout call
DELETE http://localhost:4000/logout
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6Ik1hbmkiLCJpYXQiOjE2MjU3ODE0MjQsImV4cCI6MTYyNTc4MTYwNH0.IAOS-VxPU1ztvN5ey0zT8x1NcCAO7XIw_gCQBRAJKDY"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
  "userName": "Arkrish"
}

### The Bearer token is what got from Arkrish login.
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IkFya3Jpc2giLCJpYXQiOjE2MjU3NzI1MjJ9.c2wom2aqRI-av5PO580Bc6emj1rj8qtW0wDUCZJrFPA
